class PropsDict:
    """
    """
    def __init__(self):
        self.data = {
            '1': {'Key': 'labels', 'Description': 'Atomic labels.'},
            '2': {'Key': 'coords', 'Description': 'Optimized Cartesian coordinates.'},
            '3': {'Key': 'Etot', 'Description': 'Total energy (1ev = 627.5096080305927 kcal/mol).'},
            '4': {'Key': 'e_homo_lumo', 'Description': 'Energy of HOMO and LUMO.'},
            '5': {'Key': 'polarizability', 'Description': 'Isotropic polarizability.'},
            '6': {'Key': 'dipole', 'Description': 'Dipole moment.'},
            '7': {'Key': 'quadrupole', 'Description': 'Quadrupole moment.'},
            '8': {'Key': 'zpve', 'Description': 'Zero point vibrational energy.'},
            '9': {'Key': 'rot_constants', 'Description': 'Rotational constant.'},
            '10': {'Key': 'elec_spatial_ext', 'Description': 'Electronic spatial extent.'},
            '11': {'Key': 'thermal', 'Description': 'Thermal properties at 298.15 K.'},
            '12': {'Key': 'freqs', 'Description': 'Harmonic vibrational frequencies.'},
            '13': {'Key': 'mulliken', 'Description': 'Mulliken charges.'},
            '14': {'Key': 'cv', 'Description': 'Heat capacity at 298.15 K.'},
            '15': {'Key': 'Etot', 'Description': 'Total energy.'},
            '16': {'Key': 'e_homo_lumo', 'Description': 'Energy of HOMO and LUMO.'},
            '17': {'Key': 'dipole', 'Description': 'Dipole moment.'},
            '18': {'Key': 'quadrupole', 'Description': 'Quadrupole moment.'},
            '19': {'Key': 'rot_constants', 'Description': 'Rotational constant.'},
            '20': {'Key': 'elec_spatial_ext', 'Description': 'Electronic spatial extent.'},
            '21': {'Key': 'mulliken', 'Description': 'Mulliken charges.'},
            '22': {'Key': 'transition_electric_DM', 'Description': 'Transition electric dipole moments.'},
            '23': {'Key': 'transition_velocity_DM', 'Description': 'Transition velocity dipole moments.'},
            '24': {'Key': 'transition_magnetic_DM', 'Description': 'Transition magnetic dipole moments.'},
            '25': {'Key': 'transition_velocity_QM', 'Description': 'Transition velocity quadrupole moments.'},
            '26': {'Key': 'OrbNum_HomoLumo', 'Description': 'The orbital number of HOMO and LUMO.'},
            '27': {'Key': 'Info_of_AllExcitedStates', 'Description': 'The transition contribution of 10 singlet and 10 triplet transition states.'},
            '101': {'Key': 'SMILES_PYBEL', 'Description': 'Smiles generated by pybel.'},
            '102': {'Key': 'INCHI_PYBEL', 'Description': 'Smiles generated by pybel.'},
            '103': {'Key': 'SMILES_RDKIT', 'Description': 'Smiles generated by pybel.'},
            '104': {'Key': 'INCHI_RDKIT', 'Description': 'Smiles generated by pybel.'},
            '105': {'Key': 'SMILES_RDKIT_CAN', 'Description': 'Smiles generated by pybel.'},
        }

    def get_description(self, key_id):
        """Retrieve the description of a given key ID."""
        return self.data.get(key_id, {}).get('Description', 'Key not found.')

    def get_key(self, key_id):
        """Retrieve the key name of a given key ID."""
        return self.data.get(key_id, {}).get('Key', 'Key not found.')

    def add_entry(self, key_id, key_name, description):
        """Add a new entry to the data dictionary."""
        if key_id in self.data:
            raise ValueError(f"Key ID {key_id} already exists.")
        self.data[key_id] = {'Key': key_name, 'Description': description}

    def remove_entry(self, key_id):
        """Remove an entry from the data dictionary."""
        if key_id in self.data:
            del self.data[key_id]
        else:
            raise KeyError(f"Key ID {key_id} not found.")

    def list_entries(self):
        """List all entries in the data dictionary."""
        return list(self.data.keys())

    def create_variable_from_key(self, key_id):
        """Create a dynamic variable using the key name from the dictionary."""
        variable_name = self.get_key(key_id)
        if variable_name != 'Key not found.':
            locals()[variable_name] = f"Value for {variable_name}"
            # print(f"Variable '{variable_name}' has been created with value: {locals()[variable_name]}")
            return variable_name, locals()[variable_name]
        else:
            raise KeyError("Key not found, variable not created.")

    def reference_atom_energy(self, level=1, unit=3):
        """
        level:  1 - b3lyp_bjd3 6-31g*
                2 - wb97xd 6-31g*
        unit:   1 - a.u.
                2 - eV
                3 - kcal/mol
        """
        if level == 1:
            energy = {
                1:-0.500272784186,
                6:-37.8462799747,
                7:-54.5844893898,
                8:-75.0606214291,
                9:-99.7155354580,
                }
        elif level == 2:
            energy = {
                1:-0.500607632539,
                6:-37.8302344100,
                7:-54.5680042961,
                8:-75.0362322778,
                9:-99.6907408396,
                }
        else:
            raise ValueError("level must be 1 or 2.\\1 - b3lyp_bjd3 6-31g*\\2 - wb97xd 6-31g*")

        # 1 Hartree = 27.2114 eV
        # 1 Hartree = 627.5095 kcal/mol
        if unit == 1:
            energy['unit'] = 'hartree'
            return energy
        elif unit == 2:
            energy = {atom: val * 27.2114 for atom, val in energy.items()}
            energy['unit'] = 'eV'
            return energy
        
        elif unit == 3:
            energy = {atom: val * 627.5095 for atom, val in energy.items()}
            energy['unit'] = 'kcal/mol'
            return energy 
        else:
            raise ValueError("unit must be 1 (a.u.), 2 (eV), or 3 (kcal/mol).")
    

# Example usage
if __name__ == "__main__":
    data_dict = PropsDict()
    print(data_dict.get_description('1'))  # Output: Atomic labels.
    print(data_dict.get_key('2'))          # Output: coords
    data_dict.add_entry('106', 'NEW_KEY', 'New description.')
    print(data_dict.get_description('106'))
    # Create a dynamic variable
    try:
        var_name, var_value = data_dict.create_variable_from_key('1')
        print(f"Dynamic variable created: {var_name} = {var_value}")
    except KeyError as e:
        print(e)
